apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-eigenlayer-pvc
  labels:
    app: root-eigenlayer-pvc
spec:
  storageClassName: eigenlayer-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi