apiVersion: v1
kind: PersistentVolume
metadata:
  name: root-eigenlayer-pv
  labels:
    type: root-eigenlayer-pv-label
spec:
  storageClassName: eigenlayer-sc
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root-eigenlayer"
