apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eigenlayer-pvc
  namespace: eigenlayer
  labels:
    app: eigenlayer-pvc
spec:
  storageClassName: eigenlayer-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 400Gi