#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: ironfish-mainnet-public-pv
#  namespace: mainnet-public
#  labels:
#    type: ironfish-mainnet-public-pv-label
#spec:
#  storageClassName: ironfish-sc
#  capacity:
#    storage: 400Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/ironfish-mainnet-public-dir"  #this is the path on the ebs volume itself
