kind: ConfigMap
apiVersion: v1
metadata:
  name: operator.yaml
  namespace: eigenlayer
data:
  operator.yaml: |
    operator:
        address: "0x786d65583f62f454f134442711c6f24cd8250607"
        earnings_receiver_address: "0x7992bf6Ba3879cE12ea7cd398eb8af32F3dD223C"
        
        # Operators have the option to set delegationApprover when they register.
        # If the delegationApprover is set to a nonzero value, then the delegationApprover address
        # will be required sign its approval of new delegations from Stakers to this Operator. 
        # If the default value is left as the zero address (0x000...) then all new delegations 
        # will be automatically approved without the need for any signature.
        delegation_approver_address: "0x0000000000000000000000000000000000000000"
        
        staker_opt_out_window_blocks: 0
        metadata_url: "https://dcentralab.github.io/eigenlayer-operator/metadata.json"
        
    # Navigate to https://github.com/Layr-Labs/eigenlayer-contracts?tab=readme-ov-file#deployments 
    # and locate the Proxy address for DelegationManager for your environment (Mainnet, Testnet).
    el_delegation_manager_address: 0xA44151489861Fe9e3055d95adC98FbD462B948e7
    
    eth_rpc_url: http://beacon-chain:8545
    private_key_store_path: /root/.eigenlayer/operator_keys/hord-holesky.ecdsa.key.json
    signer_type: local_keystore
    chain_id: 17000
    fireblocks:
        api_key: ""
        secret_key: ""
        base_url: ""
        vault_account_name: ""
        secret_storage_type: ""
        aws_region: ""
        timeout: 0
    web3:
        url: ""